### ISSUE TITLE
Fail to start btsync service

### ISSUE THREAD

**Issue by zinoff** [moritzdietz/pi-syncscript#10]
I have a different problem, the service doesn't start but during the install I get this error:

[OK]  Created BitTorrent Sync configuration file /etc/btsync/config.json
**/usr/bin/btsync: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.16' not found (required by /usr/bin/btsync)**
[OK]  Installed BitTorrent Sync version 

And I couldn't find a way on how to get GLIBC_2.16 - I running Wheezy .

**Comment by moritzdietz** [comment]
This doesn't really look like it is an error with my script but rather something with your Raspberry Pi.
You are probably running something like XBMC or OSMC.

Run this command and try again `sudo ln -s /lib/arm-linux-gnueabihf/libc.so.6 /lib/libc.so.6`
This should fix it. Please report back.

**Comment by zinoff** [comment]
Unfortunately it didn't work - the link is made but the script still gives the error:
**/usr/bin/btsync: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.16' not found (required by /usr/bin/btsync)**

In terms of configuration I hadn't changed anything since I last installed btsync with the previous script (I use the raspberry only for that), I just downloaded the latest version of the script uninstalled and then reinstalled and then I got the error about GLIBC (I did this because it seems like I had forgot the btsync admin password).

**Comment by moritzdietz** [comment]
What version of `gcc` and `g++` do you have installed?

**Comment by zinoff** [comment]
gcc (Raspbian 4.8.2-21~rpi3rpi1) 4.8.2

g++ 4.8

g++ - v: 
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 4.8.2-21~rpi3rpi1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.8.2 (Raspbian 4.8.2-21~rpi3rpi1)

**Comment by moritzdietz** [comment]
Ok are you using a Raspberry Pi 2? And can you check what output you get using this
`cat /etc/issue.net`
Because if this outputs 7 then you are using Wheezy and if 8 then Jessie (which is highly recommended). Please update to Jessie if you are on Wheezy.
So what I have read is that arm7l libs are compiled against GLIBC_2.16, which isn't available on RPi 2 with Raspbian. I currently don't have a Raspberry Pi 2 so the only thing I can recommend you to do is run this command and try one last thing. If that doesn't work then you have to google yourself.
`./btsync.sh http://download-cdn.getsync.com/stable/linux-arm/BitTorrent-Sync_arm.tar.gz`

**Comment by zinoff** [comment]
Yes - reverting to the old version (in the url you gave me) worked. I'll move to Jessie when I'll have a quiet weekend. 
Thank you!

**Comment by ZappoB** [comment]
Hi, I'm here with the same problem (RPi2 and Wheezy) and I don't know, how to get on... reverting to the old BTsync version worked for me, too.

Raspbian Jessie is reported to have many problems since it uses systemd, I can't get my exfat ssd automounted, thightvnc can't be autostarted and some other problems.

Wheezy still runs great with RPi2 (after all updates) but now the newest BTsync version is missing the GLIBC_2.16.

What is to expect? Will BTsync comes in future back to it's old compatibility? Or will GLIBC_2.16 comes to Wheezy on RPi2? Or can anyone point to an Jessie image, with functional automount and autostart?

Thank you very much for reading!

**Comment by zinoff** [comment]
Use the custom URL as suggested

**Comment by ZappoB** [comment]
I did, it worked, I just want to look into the future... can I never make a BTsync update?

**Comment by moritzdietz** [comment]
You can use that way with the direct URL to update your installation as well..
I might just roll back to arm build rather than having armhf.
